FROM alpine:latest
RUN apk update && \
    apk add --no-cache postgresql17-client

WORKDIR /scripts
COPY ./infrastructure/cms/database-init.sh .
RUN chmod +x ./database-init.sh

ENTRYPOINT ["./database-init.sh"]
