services:
  database:
    container_name: database
    image: postgres:latest
    env_file:
      - cms/.env
    volumes:
      - cms-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  database-init:
    container_name: database-init
    build:
      context: .
      dockerfile: infrastructure/cms/Dockerfile.init
    env_file:
      - cms/.env
    restart: on-failure
    depends_on:
      - database

  strapi:
    container_name: cms
    build:
      context: .
      dockerfile: infrastructure/cms/Dockerfile.cms
    env_file:
      - cms/.env
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=database
    ports:
      - 1337
    restart: always
    depends_on:
      - database-init

volumes:
  cms-data:
